### ISSUE TITLE
PyPI pacakge

### ISSUE THREAD

**Issue by dhirschfeld** [amazon-science/chronos-forecasting#10]
A PyPI package would be great to have though it would be problematic at present as there already exists a `chronos-forecast` package which installs into the `chronos` namespace:
* https://pypi.org/project/chronos-forecast/
* https://github.com/boris-shabash/Chronos

**Comment by dhirschfeld** [comment]
The existing package doesn't seem to be actively maintained so maybe they'd be willing to give up name and you could publish a version 1.0.0 signifying an api break?

**Comment by canerturkmen** [comment]
Hey @dhirschfeld  thanks for raising this! At this time this codebase is intended only for research / reproducibility purposes. Chronos will be actively maintained and developed within [AutoGluon-TimeSeries](https://github.com/autogluon/autogluon), already in progress here: https://github.com/autogluon/autogluon/pull/3978

Hopefully AutoGluon will make it much easier to test Chronos, compare with a host of existing forecasting approaches, and easily create cloud deployments of Chronos. 

Hope this helps!
