### ISSUE TITLE
basic inference packages setup -> finetuning setup

### ISSUE THREAD

**Issue by CoCoNuTeK** [amazon-science/chronos-forecasting#104]
I would like to ask if i already have chronos conda environment for inference setup, can i just run the pip install "chronos[training] @ git+https://github.com/amazon-science/chronos-forecasting.git" inside of my already existing conda env as it will just install a few missing packages? or is it advised to have 2 separate environments?

**Comment by abdulfatir** [comment]
Using the same environment should be okay.
