### ISSUE TITLE
[BUG]  NotImplementedError: The operator 'aten::isin.Tensor_Tensor_out' is not currently implemented for the MPS device. 

### ISSUE THREAD

**Issue by Nucleon729** [amazon-science/chronos-forecasting#141]
Hi,

when trying to run the example script on macOS on a macM1 Max, using mps, I get this error:

> NotImplementedError: The operator 'aten::isin.Tensor_Tensor_out' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.

does it means I can't run chronos natively on MPS?

Kind regards,

**Comment by lostella** [comment]
@Nucleon729 as suggested by the error message, setting `PYTORCH_ENABLE_MPS_FALLBACK=1` will make it work. Just run

```
export PYTORCH_ENABLE_MPS_FALLBACK=1
```

in your terminal before executing the example snippet.

**Comment by abdulfatir** [comment]
@Nucleon729 Some changes in `transformers` broke MPS support. Please install the following version:

```sh
pip install transformers~=4.39.0
```

Also note that `bfloat16` may not be supported on MPS, so you should change the `torch_dtype` to `torch.float32`.

**Comment by abdulfatir** [comment]
Opened an issue in `transformers`: https://github.com/huggingface/transformers/issues/31737

**Comment by abdulfatir** [comment]
Fix for the above issue was merged.
