### ISSUE TITLE
Faster manual retrieval than the pipeline. 

### ISSUE THREAD

**Issue by amir-elahi** [amazon-science/chronos-forecasting#190]
Hello, hope you are doing well. I am playing around with Chronos and found out if I retrieve the forecasts manually rather than using the pipeline it is much faster on outputting. I am using CPU now. I profiled the two codes and it looks like they are calling different functions the same amount of time, but just faster. Do you have an idea of why? Or am I missing something here?

My code for profiling the pipeline and manual retrieval:

```
##### the github issue.

import torch
from chronos import ChronosPipeline
from transformers import T5ForConditionalGeneration
from transformers import set_seed

set_seed(42)

pipeline = ChronosPipeline.from_pretrained(
    "amazon/chronos-t5-small",
    device_map="cpu",  # use "cpu" for CPU inference and "mps" for Apple Silicon
    torch_dtype=torch.bfloat16,
)

original_model = T5ForConditionalGeneration.from_pretrained("amazon/chronos-t5-small")


# Pass  two lines to the model.
context1 = torch.linspace(0, 100, 512).unsqueeze(0)
context2 = (context1.clone()[0,:]*2).unsqueeze(0)
context = torch.cat((context1, context2), dim=0)


############################################
# profile the manual retrieval
import cProfile
import pstats
from io import StringIO

def profile_code(context=context):
    predictions_from_original_model = []
    remaining = 50

    while remaining > 0:
        token_ids, attention_mask, scale = pipeline.tokenizer.context_input_transform(
            context
        )
        samples = original_model.generate(
                    input_ids=token_ids,
                    attention_mask=attention_mask, 
                    min_new_tokens=50,
                    max_new_tokens=50,
                    do_sample=True,
                    # num_samples= 1,
                    num_return_sequences=1,
                    eos_token_id=pipeline.model.config.eos_token_id,
                    pad_token_id=pipeline.model.config.pad_token_id)
        

        samples = samples[..., 1:]
        samples = samples.reshape(token_ids.size(0), 1, -1)
        
        prediction = pipeline.tokenizer.output_transform(
            samples.to(scale.device), scale
        )

        predictions_from_original_model.append(prediction)
        remaining -= prediction.shape[-1]

        if remaining <= 0:
            break

        context = torch.cat(
            [context, prediction.median(dim=1).values], dim=-1
        )

# Profile the function
pr = cProfile.Profile()
pr.enable()
profile_code()
pr.disable()

# Print the profiling results
s = StringIO()
sortby = 'cumulative'
ps = pstats.Stats(pr, stream=s).strip_dirs().sort_stats(sortby)
ps.print_stats()
print(s.getvalue())


##############################################
# profile the pipeline retrieval:
import cProfile
import pstats
from io import StringIO

def profile_code():
    forecast = pipeline.predict(context=context, prediction_length=50, num_samples=1)

# Profile the function
pr = cProfile.Profile()
pr.enable()
profile_code()
pr.disable()

# Print the profiling results
s = StringIO()
sortby = 'cumulative'
ps = pstats.Stats(pr, stream=s).strip_dirs().sort_stats(sortby)
ps.print_stats()
print(s.getvalue())
```

### The profile of my code is:

         120339 function calls (102565 primitive calls) in 2.359 seconds

   Ordered by: cumulative time

| ncalls   | tottime | percall | cumtime | percall | filename:lineno(function)                     |
|----------|---------|---------|---------|---------|------------------------------------------------|
| 2        | 0.000   | 0.000   | 2.360   | 1.180   | interactiveshell.py:3541(run_code)             |
| 2        | 0.000   | 0.000   | 2.360   | 1.180   | {built-in method builtins.exec}                |
| 1        | 0.000   | 0.000   | 2.360   | 2.360   | 765372344.py:31(profile_code)                  |
| 1        | 0.000   | 0.000   | 2.359   | 2.359   | _contextlib.py:113(decorate_context)           |
| 1        | 0.000   | 0.000   | 2.359   | 2.359   | utils.py:1587(generate)                        |
| 7420/51  | 0.018   | 0.000   | 2.264   | 0.044   | module.py:1549(_wrapped_call_impl)             |
| 7420/51  | 0.049   | 0.000   | 2.264   | 0.044   | module.py:1555(_call_impl)                     |
| 51       | 0.010   | 0.000   | 2.189   | 0.043   | modeling_t5.py:969(forward)                    |
| 306      | 0.015   | 0.000   | 2.130   | 0.007   | modeling_t5.py:654(forward)                    |
| 1        | 0.013   | 0.013   | 1.897   | 1.897   | utils.py:2888(_sample)                         |
| 50       | 0.004   | 0.000   | 1.804   | 0.036   | modeling_t5.py:1638(forward)                   |
| 606      | 0.113   | 0.000   | 1.301   | 0.002   | modeling_t5.py:445(forward)                    |
| 2498     | 0.010   | 0.000   | 0.994   | 0.000   | linear.py:116(forward)                         |
| **2498**     | **0.980**   | **0.000**   | **0.980**   | **0.000**   | **{built-in method torch._C._nn.linear}**          |

     
### The pipeline
         120925 function calls (103283 primitive calls) in 23.337 seconds

 | ncalls   | tottime | percall | cumtime | percall | filename:lineno(function)                     |
|----------|---------|---------|---------|---------|------------------------------------------------|
| 2        | 0.000   | 0.000   | 23.337  | 11.669  | interactiveshell.py:3541(run_code)             |
| 2        | 0.000   | 0.000   | 23.337  | 11.669  | {built-in method builtins.exec}                |
| 1        | 0.000   | 0.000   | 23.337  | 23.337  | 765372344.py:88(profile_code)                  |
| 1        | 0.000   | 0.000   | 23.337  | 23.337  | chronos.py:443(predict)                        |
| 7421/1   | 0.018   | 0.000   | 23.336  | 23.336  | module.py:1549(_wrapped_call_impl)             |
| 7421/1   | 0.045   | 0.000   | 23.336  | 23.336  | module.py:1555(_call_impl)                     |
| 1        | 0.000   | 0.000   | 23.336  | 23.336  | chronos.py:301(forward)                        |
| 1        | 0.000   | 0.000   | 23.336  | 23.336  | _contextlib.py:113(decorate_context)           |
| 1        | 0.000   | 0.000   | 23.336  | 23.336  | utils.py:1587(generate)                        |
| 51       | 0.009   | 0.000   | 23.068  | 0.452   | modeling_t5.py:969(forward)                    |
| 306      | 0.013   | 0.000   | 23.009  | 0.075   | modeling_t5.py:654(forward)                    |
| 2498     | 0.010   | 0.000   | 18.928  | 0.008   | linear.py:116(forward)                         |
| **2498**     | **18.916**  | **0.008**   | **18.916**  | **0.008**   | <b>{built-in method torch._C._nn.linear}</b>          |

**Comment by lostella** [comment]
@amir-elahi hi, it looks like you're initializing the model in two different ways:

```python
pipeline = ChronosPipeline.from_pretrained(
    "amazon/chronos-t5-small",
    device_map="cpu",  # use "cpu" for CPU inference and "mps" for Apple Silicon
    torch_dtype=torch.bfloat16,
)
```

vs

```python
original_model = T5ForConditionalGeneration.from_pretrained("amazon/chronos-t5-small")
```

In the latter case, float32 will be used by default, which is faster on CPU (bfloat16 is emulated on CPU). If you comment the `torch_dtype` setting when constructing `pipeline`, you'll see similar performance.
