### ISSUE TITLE
[BUG]Chronos pip install not working

### ISSUE THREAD

**Issue by Hstellar** [amazon-science/chronos-forecasting#235]
With current version `pip install "chronos[training] @ git+https://github.com/amazon-science/chronos-forecasting.git"` and `pip install "chronos[evaluation] @ git+https://github.com/amazon-science/chronos-forecasting.git"` gives below error:

```
  WARNING: Generating metadata for package chronos produced metadata for project name chronos-forecasting. Fix your #egg=chronos fragments.
Discarding git+https://github.com/amazon-science/chronos-forecasting.git: Requested chronos-forecasting from git+https://github.com/amazon-science/chronos-forecasting.git (from chronos@ git+https://github.com/amazon-science/chronos-forecasting.git) has inconsistent name: expected 'chronos', but metadata has 'chronos-forecasting'
ERROR: Could not find a version that satisfies the requirement chronos (unavailable) (from versions: 0.1, 0.1.1, 0.1.2, 0.2, 0.3)
ERROR: No matching distribution found for chronos (unavailable)
```

python version: 3.10.12

Although v1.2.0 works: `chronos[training] @ git+https://github.com/amazon-science/chronos-forecasting.git@v1.20`

**Comment by abdulfatir** [comment]
@Hstellar Thank you for raising this! 

We recently changed the package name in `pyproject.toml` from `chronos` to `chronos-forecasting` which causes this issue. Please use:

```
pip install "chronos-forecasting[training] @ git+https://github.com/amazon-science/chronos-forecasting.git"
```

I am updating the README to fix the command.

**Comment by Hstellar** [comment]
@abdulfatir Thank you! This solves the issue.
