### ISSUE TITLE
Question regarding evaluation dataset and paper results

### ISSUE THREAD

**Issue by zeyihou** [amazon-science/chronos-forecasting#242]
Thank you for your great work!
From the provided YAML files for the evaluation dataset, it appears that only the last prediction_length of each dataset is used for evaluation. This means the evaluation is based on a very small portion of the dataset (i.e., the last segment).
For example, if prediction_length is 24 and the dataset length is 1000, only the last 24 time steps are used. Are the results reported in the paper based on this testing method (i.e., using only the last prediction_length)

**Comment by lostella** [comment]
Closing in favor of https://github.com/amazon-science/chronos-forecasting/discussions/241 to avoid duplication
