### ISSUE TITLE
Training with past X and Y to Predict Y and Forecasting with X for next 6 months to predict Y

### ISSUE THREAD

**Issue by suryan24297** [amazon-science/chronos-forecasting#37]
Is it possible to train model with past X(Time Period) and Y(Dependent) data to Predict Z and then forecast it with future Y(Dependent data available for next 6 months) to predict Z for those 6 months with X(Time Period) and Y(Dependent Data) data?

**Comment by abdulfatir** [comment]
@suryan24297 I am not sure I understand. Could you elaborate?

**Comment by suryan24297** [comment]
> @suryan24297 I am not sure I understand. Could you elaborate?

Bivariate time series forecasting, is it possible to tweak the existing model to work on that ?

**Comment by abdulfatir** [comment]
The models currently only support univariate time series. See #13.
