### ISSUE TITLE
If the history context is larger than 512

### ISSUE THREAD

**Issue by ForestsKing** [amazon-science/chronos-forecasting#38]
Does chronos truncate the history context if it is larger than 512? If it will, can I turn off this limitation.

**Comment by abdulfatir** [comment]
It does: https://github.com/amazon-science/chronos-forecasting/blob/96cedec3fa9795c9bd58650080643e2b68bd3a6e/src/chronos/chronos.py#L140-L141

You can modify the code yourself, if you'd like to test without truncation but we have not really tested this setting of training on a specific context length and testing on a larger one. I'm not sure if it would work. If you decide to give it a go, I would be happy to hear your thoughts/results.

**Comment by ForestsKing** [comment]
ok, thanks!
