### ISSUE TITLE
Prediction changes for every run

### ISSUE THREAD

**Issue by harshitv804** [amazon-science/chronos-forecasting#54]
Hi, I was trying to fine tuning the hyperparameters and every time I run the .predict, it gives me different predictions (sometimes converges very good, sometimes very bad). Any way to solve this Issue? 

Thank you!

**Comment by lostella** [comment]
Hi @harshitv804, see the discussion in #18

**Comment by lostella** [comment]
The recommended way is

```python
import transformers
transformers.set_seed(0)
```

**Comment by harshitv804** [comment]
It's working. thanks !
