### ISSUE TITLE
How to scale binned predictor value back to real raw value scala.

### ISSUE THREAD

**Issue by iphyer** [amazon-science/chronos-forecasting#57]
I have a question about scaling back to the raw data scale in the paper. I've read both the paper and the reference paper on quantization of time series, but I'm still unsure. I understand that we transformed the data and then binned it, the the LLM will predict a bin index. Then my question is, how do we scale it back to the raw data scale? Do we use the mid-point value of the bin? I'm concerned that this approach may introduce a resolution issue in the results.
Thanks!

**Comment by lostella** [comment]
Hi @iphyer, the de-tokenization precisely uses the center point of the bin, see eq (1) in the paper. Then this is scaled back by the same factor used on the input size. The whole thing happens [here](https://github.com/amazon-science/chronos-forecasting/blob/6ae390f2912c6d0521a1d5860f8f2aeb4089ccee/src/chronos/chronos.py#L180) in the code. There are of course some limitations to this approach that one should be aware of (see Fig. 16 in the paper and associated paragraph) but this does not seem to be a problem for many datasets.

**Comment by iphyer** [comment]
Thank you for the timely answer, really appreciate!
