### ISSUE TITLE
ValueError: `decoder_start_token_id` or `bos_token_id` has to be defined for encoder-decoder generation, cant get Chronos to run today

### ISSUE THREAD

**Issue by emitby** [amazon-science/chronos-forecasting#76]
Yesterday Chronos was working great, today for some reason its throwing this error, even with the sample code with the airline passenger data:

ValueError: `decoder_start_token_id` or `bos_token_id` has to be defined for encoder-decoder generation

Chronos is throwing the same error for both AWS Sagemaker in Jupyter Lab and also ML-Azure, so the error seems to be platform independent.

thanks,

**Comment by lostella** [comment]
Hi @emitby, thanks for opening the issue. This seems a problem with the recent transformers 4.41. Solution is to downgrade to 4.40 for now, while we look into this deeper.

**Comment by lostella** [comment]
@emitby #77 fixed this. On a fresh environment, the README instructions will now work. On existing environments, one should ensure to have `transformers<4.41` (e.g. `pip install transformers<4.41`).

**Comment by abdulfatir** [comment]
Opened an issue in transformers: https://github.com/huggingface/transformers/issues/30892
