### ISSUE TITLE
Pretraining dataset and recipe

### ISSUE THREAD

**Issue by Otsutsukii** [amazon-science/chronos-forecasting#84]
Hello, would it be possible to also release the pretraining dataset ( used for TSmixup), and maybe a mention of a successful training recipe. 

I would like to try to pretrain from scratch as well, and also extending the vocabulary size wayyyyy more, and with a custom dataset.

**Comment by abdulfatir** [comment]
@Otsutsukii Thanks for your interest. We are working on releasing the individual datasets and TSMixup script. I will let you know here once we have an update.

**Comment by abdulfatir** [comment]
**Update**: We have just open-sourced the datasets used in the paper (thanks @shchur!). Please check the updated [README](https://github.com/amazon-science/chronos-forecasting). We have also released an evaluation script and backtest configs to compute the WQL and MASE numbers as reported in the paper.

**Comment by lostella** [comment]
Closing in favor of #150
