### ISSUE TITLE
Performance Metric for Chronos

### ISSUE THREAD

**Issue by yeongnamtan** [amazon-science/chronos-forecasting#96]
hi, I am new to Chronos.

How do I evaluate the performance of forecast ?  is there a way to do BACKTESTING ?

Do we use MAE ?

**Comment by abdulfatir** [comment]
**Update**: We have just open-sourced the datasets used in the paper (thanks @shchur!). Please check the updated [README](https://github.com/amazon-science/chronos-forecasting). We have also released an evaluation script and backtest configs to compute the WQL and MASE numbers as reported in the paper. Please follow the instructions [in this README](https://github.com/amazon-science/chronos-forecasting/tree/main/scripts#evaluating-chronos-models) to evaluate on the in-domain and zero-shot benchmarks.
